services:
    oro_apruve.connection.validator.request.factory.get_merchant_request:
        class: 'Oro\Bundle\ApruveBundle\Connection\Validator\Request\Factory\Merchant\GetMerchantRequestApruveConnectionValidatorRequestFactory'
        public: false
        arguments:
            - '@oro_apruve.client.request.merchant.factory'
            - '@oro_security.encoder.mcrypt'

    oro_apruve.connection.validator.result.factory.get_merchant_request:
        class: 'Oro\Bundle\ApruveBundle\Connection\Validator\Result\Factory\Merchant\GetMerchantRequestApruveConnectionValidatorResultFactory'
        public: false

    oro_apruve.connection.validator:
        class: 'Oro\Bundle\ApruveBundle\Connection\Validator\ApruveConnectionValidator'
        arguments:
            - '@oro_apruve.client.settings.factory.basic'
            - '@oro_apruve.connection.validator.request.factory.get_merchant_request'
            - '@oro_apruve.connection.validator.result.factory.get_merchant_request'
            - '@logger'
