services:

    oro_apruve.form.type.apruve_settings:
        class: 'Oro\Bundle\ApruveBundle\Form\Type\ApruveSettingsType'
        arguments:
            - '@oro_apruve.integration.transport'
            - '@oro_security.form.data_transformer.factory.crypted_data'
        tags:
            - { name: form.type }

    oro_apruve.form.type.webhook_token:
        class: 'Oro\Bundle\ApruveBundle\Form\Type\WebhookTokenType'
        arguments:
            - '@oro_security.generator.random_token'
        tags:
            - { name: form.type }
