services:
    oro_apruve.integration.channel:
        class: 'Oro\Bundle\ApruveBundle\Integration\ApruveChannelType'
        tags:
            - { name: oro_integration.channel, type: apruve }

    oro_apruve.integration.transport:
        class: 'Oro\Bundle\ApruveBundle\Integration\ApruveTransport'
        tags:
            - { name: oro_integration.transport, type: apruve, channel_type: apruve }
