parameters:
    oro_apruve.method.identifier_prefix.apruve: 'apruve'

services:
    oro_apruve.method.generator.identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%oro_apruve.method.identifier_prefix.apruve%'

    oro_apruve.method.config.factory:
        class: 'Oro\Bundle\ApruveBundle\Method\Config\Factory\ApruveConfigFactory'
        public: false
        arguments:
            - '@oro_locale.helper.localization'
            - '@oro_apruve.method.generator.identifier'
            - '@oro_security.encoder.mcrypt'
            - '@logger'

    oro_apruve.method.config.provider:
        class: 'Oro\Bundle\ApruveBundle\Method\Config\Provider\ApruveConfigProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@logger'
            - '@oro_apruve.method.config.factory'

    oro_apruve.method.apruve.factory:
        class: 'Oro\Bundle\ApruveBundle\Method\Factory\ApruvePaymentMethodFactory'
        public: false
        arguments:
            - '@oro_apruve.method.executor.payment_action'
            - '@oro_apruve.apruve.provider.supported_currencies'

    oro_apruve.method.apruve.provider:
        class: 'Oro\Bundle\ApruveBundle\Method\Provider\ApruvePaymentMethodProvider'
        public: false
        arguments:
            - '@oro_apruve.method.config.provider'
            - '@oro_apruve.method.apruve.factory'
        tags:
            - { name: oro_payment.payment_method_provider }

    oro_apruve.method.view.factory:
        class: 'Oro\Bundle\ApruveBundle\Method\View\Factory\ApruvePaymentMethodViewFactory'
        public: false

    oro_apruve.method.view.provider:
        class: 'Oro\Bundle\ApruveBundle\Method\View\Provider\ApruvePaymentMethodViewProvider'
        public: false
        arguments:
            - '@oro_apruve.method.config.provider'
            - '@oro_apruve.method.view.factory'
        tags:
            - { name: oro_payment.payment_method_view_provider }
