services:
    oro_apruve.method.executor.payment_action:
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\Executor\PaymentActionExecutor'
        public: false
        lazy: true
        calls:
            - ['addPaymentAction', ['@oro_apruve.method.payment_action.purchase']]
            - ['addPaymentAction', ['@oro_apruve.method.payment_action.authorize']]
            - ['addPaymentAction', ['@oro_apruve.method.payment_action.invoice']]
            - ['addPaymentAction', ['@oro_apruve.method.payment_action.shipment']]
            - ['addPaymentAction', ['@oro_apruve.method.payment_action.capture']]
            - ['addPaymentAction', ['@oro_apruve.method.payment_action.cancel']]

    oro_apruve.method.payment_action.abstract:
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\AbstractPaymentAction'
        arguments:
            - '@oro_payment.context.factory.transaction_payment_context'
        abstract: true

    oro_apruve.method.payment_action.purchase:
        parent: oro_apruve.method.payment_action.abstract
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\PurchasePaymentAction'
        arguments:
            - '@oro_apruve.apruve.factory.order'
            - '@oro_apruve.apruve.generator.order_secure_hash'
        calls:
            - [setLogger, ['@logger']]
        public: false
        lazy: true

    oro_apruve.method.payment_action.authorize:
        parent: oro_apruve.method.payment_action.abstract
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\AuthorizePaymentAction'
        public: false
        lazy: true

    oro_apruve.method.payment_action.invoice:
        parent: oro_apruve.method.payment_action.abstract
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\InvoicePaymentAction'
        arguments:
            - '@oro_apruve.apruve.factory.invoice'
            - '@oro_apruve.apruve.factory.invoice_from_response'
            - '@oro_apruve.client.config.factory.basic'
            - '@oro_apruve.client.request.invoice.factory'
        calls:
            - [setLogger, ['@logger']]
        public: false
        lazy: true

    oro_apruve.method.payment_action.shipment:
        parent: oro_apruve.method.payment_action.abstract
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\ShipmentPaymentAction'
        arguments:
            - '@oro_apruve.apruve.factory.shipment'
            - '@oro_apruve.apruve.factory.shipment_from_response'
            - '@oro_apruve.client.config.factory.basic'
            - '@oro_apruve.client.request.shipment.factory'
        calls:
            - [setLogger, ['@logger']]
        public: false
        lazy: true

    oro_apruve.method.payment_action.capture:
        parent: oro_apruve.method.payment_action.abstract
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\CapturePaymentAction'
        public: false
        lazy: true

    oro_apruve.method.payment_action.cancel:
        parent: oro_apruve.method.payment_action.abstract
        class: 'Oro\Bundle\ApruveBundle\Method\PaymentAction\CancelPaymentAction'
        public: false
        lazy: true
