services:

    oro_apruve.repository.apruve_settings:
        class: 'Oro\Bundle\ApruveBundle\Entity\Repository\ApruveSettingsRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\ApruveBundle\Entity\ApruveSettings'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    oro_apruve.provider.shipping_amount:
        class: 'Oro\Bundle\ApruveBundle\Provider\ShippingAmountProvider'
        arguments:
            - '@oro_payment.provider.surcharge'
        lazy: true
        public: false

    oro_apruve.provider.tax_amount:
        class: 'Oro\Bundle\ApruveBundle\Provider\TaxAmountProvider'
        arguments:
            - '@oro_tax.manager.tax_manager'
        calls:
            - ['setLogger', ['@logger']]
        lazy: true
        public: false

    oro_apruve.layout.provider.apruvejs_uri:
        class: 'Oro\Bundle\ApruveBundle\Layout\Provider\ApruveJsUriProvider'
        arguments:
            - '@oro_apruve.method.config.provider'
        tags:
            - { name: layout.data_provider, alias: oro_apruve_apruvejs_uri_provider }

    oro_apruve.action.invoice_payment_transaction:
        class: 'Oro\Bundle\ApruveBundle\PaymentTransaction\Action\PaymentTransactionInvoiceAction'
        parent: oro_payment.action.payment_method_action.abstract
        tags:
            - { name: oro_action.action, alias: oro_apruve_payment_transaction_invoice }
