services:

    oro_apruve.repository.apruve_settings:
        class: 'Oro\Bundle\ApruveBundle\Entity\Repository\ApruveSettingsRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\ApruveBundle\Entity\ApruveSettings'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    Oro\Bundle\ApruveBundle\Entity\Repository\ApruveSettingsRepository:
        alias: oro_apruve.repository.apruve_settings

    oro_apruve.provider.shipping_amount:
        class: 'Oro\Bundle\ApruveBundle\Provider\ShippingAmountProvider'
        arguments:
            - '@oro_payment.provider.surcharge'
        lazy: true
        public: false

    oro_apruve.provider.tax_amount:
        class: 'Oro\Bundle\ApruveBundle\Provider\TaxAmountProvider'
        arguments:
            - '@oro_tax.provider.tax_amount'
        calls:
            - ['setLogger', ['@logger']]
        lazy: true
        public: false
        tags:
            - { name: monolog.logger, channel: oro_apruve }

    oro_apruve.action.invoice_payment_transaction:
        class: 'Oro\Bundle\ApruveBundle\PaymentTransaction\Action\PaymentTransactionInvoiceAction'
        parent: oro_payment.action.payment_method_action.abstract
        tags:
            - { name: oro_action.action, alias: oro_apruve_payment_transaction_invoice }
