security:
    firewalls:
        appruve_webhook:
            pattern:                        ^%web_backend_prefix%/apruve/webhook/*
            security:                       false
            anonymous:                      true
